image: docker:latest
services:
- docker:dind

stages:
- build


before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t registry.gitlab.com/agora-wspolnoty/backend-app -f src/docker/Dockerfile .
    - docker push registry.gitlab.com/agora-wspolnoty/backend-app