stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: http://aws.agora-wspolnoty.pl:9080/ScriptingContainerEJB/JythonBeanService?wsdl
  only:
  - Sprint-26
